version: '3.8'

services:
  # Frontend (Next.js)
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
    depends_on:
      - api
      - redis
    networks:
      - shockwave-network

  # Backend API (FastAPI)
  api:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/shockwave
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
      - simulation_data:/app/data
    networks:
      - shockwave-network

  # Celery Worker
  worker:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    command: celery -A app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/shockwave
      - REDIS_URL=redis://redis:6379
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - db
      - redis
    volumes:
      - ./api:/app
      - simulation_data:/app/data
    networks:
      - shockwave-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=shockwave
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - shockwave-network

  # Redis (for Celery and caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - shockwave-network

  # Flower (Celery monitoring)
  flower:
    build:
      context: ./api
      dockerfile: api.Dockerfile
    command: celery -A app.celery flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
    networks:
      - shockwave-network

volumes:
  postgres_data:
  redis_data:
  simulation_data:

networks:
  shockwave-network:
    driver: bridge
